spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quest_game_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true